interface IRepos {
    archive_url: null | string;
    archived: boolean;
    assignees_url: null | string;
    blobs_url: null | string;
    branches_url: null | string;
    clone_url: null | string;
    collaborators_url: null | string;
    comments_url: null | string;
    commits_url: null | string;
    compare_url: null | string;
    contents_url: null | string;
    contributors_url: null | string;
    created_at: string;
    default_branch: string;
    deployments_url: null | string;
    description: string;
    disabled: boolean;
    downloads_url: null | string;
    events_url: null | string;
    fork: boolean;
    forks: number;
    forks_count: number;
    forks_url: null | string;
    full_name: string;
    git_commits_url: null | string;
    git_refs_url: null | string;
    git_tags_url: null | string;
    git_url: null | string;
    has_downloads: boolean;
    has_issues: boolean;
    has_pages: boolean;
    has_projects: boolean;
    has_wiki: boolean;
    homepage: null | string;
    hooks_url: null | string;
    html_url: null | string;
    id: number;
    issue_comment_url: null | string;
    issue_events_url: null | string;
    issues_url: null | string;
    keys_url: null | string;
    labels_url: null | string;
    language: null | string;
    languages_url: null | string;
    license: {
        key: string;
        name: string;
        spdx_id: string;
        url: string;
        node_id: string;
    };
    merges_url: null | string;
    milestones_url: null | string;
    mirror_url: null | string;
    name: string;
    node_id: string;
    notifications_url: null | string;
    open_issues: number;
    open_issues_count: number;
    owner: unknown;
    private: boolean;
    pulls_url: null | string;
    pushed_at: string;
    releases_url: null | string;
    size: number;
    ssh_url: null | string;
    stargazers_count: number;
    stargazers_url: null | string;
    statuses_url: null | string;
    subscribers_url: null | string;
    subscription_url: null | string;
    svn_url: null | string;
    tags_url: null | string;
    teams_url: null | string;
    trees_url: null | string;
    updated_at: null | string;
    url: null | string;
    watchers: number;
    watchers_count: number;
}

export default IRepos;
